version: '3.4'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=contacts
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_NAME=contacts
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure